### PR TITLE
[base] Fix ginger_geo_nearby with negative lat/lng

### LINKED ISSUE #370: Negative lat or lng values breaks ginger_geo_nearby
For example with entoen.nu on acceptation server when using zipcode 1001AB.

This results into an order by like: 
`order by (pivot_location_lat-30.4226748)*(pivot_location_lat-30.4226748) + (pivot_location_lng--87.23802219999999)*(pivot_location_lng--87.23802219999999)`

and psql error message:

> syntax error at end of input

When using positive lat & lng the query succeeds.

### PR DESCRIPTION
**Pull request by ddeboer**
* Re-use Zotonic's geo search instead of duplicating the code.

Fix #370.

### CODE REVIEW

**Comment by Dirklectisch** [comment]
@ddeboer I think your PR loses support for all `ginger_search` arguments doesn't it?

https://github.com/driebit/ginger/pull/371/commits/d372381e5459ec53218dc699a901d4303c6ff094#diff-40ce47d7d46c5f5b9332dab161106032L30

File: modules/mod_ginger_base/support/ginger_geo_search.erl [hunk 1]
```diff
@@ -19,45 +19,49 @@ search_query(#search_query{search={ginger_geo, Args}}, Context) ->
...
-            z_convert:to_list(LngMax)
-        ],
-        " "
-    ),
-    SearchSql = and_where(BaseSearch, WhereStr),
+    %% Rebuild WHERE and ORDER BY because argument positions have shifted.
+    GeoWhere = arg(1, Placeholders) ++ " < pivot_location_lat AND " ++ arg(2, Placeholders) ++ "< pivot_location_lng "
+            ++ " AND pivot_location_lat < " ++ arg(3, Placeholders) ++ " AND pivot_location_lng < " ++ arg(4, Placeholders),
+    GeoOrder = "(pivot_location_lat-" ++ arg(5, Placeholders) ++ ")^2"
+        ++ " + (pivot_location_lng-" ++ arg(6, Placeholders) ++ ")^2",
```
Comment (ddeboer) [inline modules/mod_ginger_base/support/ginger_geo_search.erl]: This solves the actual bug: by keeping the coordinate floats as query parameters (instead of merging them into one query string), escaping any negative floats works properly.

**Comment by ddeboer** [comment]
> I think your PR loses support for all ginger_search arguments doesn't it?

Ahum, yes, so it does. I think my drive to simplify turned into an oversimplification. 

Now adapted to keep the Ginger search params.

File: modules/mod_ginger_base/support/ginger_geo_search.erl (hunk 1 above)
Comment (ddeboer) [reply modules/mod_ginger_base/support/ginger_geo_search.erl]: The original query has `A*A` but `A^2` is of course the same and doesn’t need the argument repetition.
